# Generated by Django 5.2.6 on 2025-09-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('data', models.BinaryField(default=b'')),
                ('content_type', models.CharField(default='image/jpeg', max_length=50)),
            ],
        ),
    ]
