# Generated by Django 5.2.6 on 2025-09-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facelockapp', '0002_uploadedimage_delete_faceuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='content_type',
            field=models.CharField(default='image/jpeg', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='data',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
